package clm.demo.specifications;

import clm.demo.dto.requests.SearchRequest;
import clm.demo.models.Contract;
import jakarta.persistence.criteria.Predicate;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA Specification for building dynamic search queries.
 * Handles null-safe filtering where only non-null fields in SearchRequest are applied.
 * All conditions are combined with AND (intersection) logic.
 */
@Component
public class ContractSpecification {

    /**
     * Creates a Specification that applies all non-null filters from the SearchRequest.
     * Only fields with non-null/non-empty values are included in the query.
     *
     * @param request the search request containing filter criteria
     * @return a Specification that combines all applicable filters with AND logic
     */
    public Specification<Contract> buildSearchSpecification(SearchRequest request) {
        return (root, query, criteriaBuilder) -> {
            List<Predicate> predicates = new ArrayList<>();

            // 1. Filter by notes (case-insensitive substring match)
            if (request.notes() != null && !request.notes().isBlank()) {
                predicates.add(criteriaBuilder.like(
                        criteriaBuilder.lower(root.get("notes")),
                        "%" + request.notes().toLowerCase() + "%"
                ));
            }

            // 2. Filter by contract status
            if (request.contractStatus() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("contractStatus"),
                        request.contractStatus()
                ));
            }

            // 3. Filter by client ID
            if (request.clientId() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("clientId"),
                        request.clientId()
                ));
            }

            // 4. Filter by generated by user ID
            if (request.generatedBy() != null) {
                predicates.add(criteriaBuilder.equal(
                        root.get("generatedBy"),
                        request.generatedBy()
                ));
            }

            // 5. Filter by template name (case-insensitive substring match)
            if (request.templateName() != null && !request.templateName().isBlank()) {
                predicates.add(criteriaBuilder.like(
                        criteriaBuilder.lower(root.get("contractTemplate").get("templateName")),
                        "%" + request.templateName().toLowerCase() + "%"
                ));
            }

            // 6. Filter by template description (case-insensitive substring match)
            if (request.templateDescription() != null && !request.templateDescription().isBlank()) {
                predicates.add(criteriaBuilder.like(
                        criteriaBuilder.lower(root.get("contractTemplate").get("description")),
                        "%" + request.templateDescription().toLowerCase() + "%"
                ));
            }

            // 7. Filter by created date range
            if (request.createdAfter() != null) {
                LocalDateTime startDateTime = request.createdAfter().atStartOfDay();
                predicates.add(criteriaBuilder.greaterThanOrEqualTo(
                        root.get("createdAt"),
                        startDateTime
                ));
            }

            if (request.createdBefore() != null) {
                LocalDateTime endDateTime = request.createdBefore().atTime(LocalTime.MAX);
                predicates.add(criteriaBuilder.lessThanOrEqualTo(
                        root.get("createdAt"),
                        endDateTime
                ));
            }

            // Return empty specification if no filters provided
            if (predicates.isEmpty()) {
                return criteriaBuilder.conjunction();
            }

            // Combine all predicates with AND (intersection)
            return criteriaBuilder.and(predicates.toArray(new Predicate[0]));
        };
    }
}

