-- =============================================================================
-- V2__optimize_search_indexes.sql
-- Adds performance-optimized indexes for the search functionality.
-- Supports efficient filtering on frequently searched columns.
-- =============================================================================

-- Index for searching by contract status
CREATE INDEX IF NOT EXISTS idx_generated_contract_status
    ON contracts.generated_contract (contract_status);

-- Index for searching by client ID
CREATE INDEX IF NOT EXISTS idx_generated_contract_client_id
    ON contracts.generated_contract (client_id);

-- Index for searching by generated by user ID
CREATE INDEX IF NOT EXISTS idx_generated_contract_generated_by
    ON contracts.generated_contract (generated_by);

-- Composite index for status + client_id (common combined filter)
CREATE INDEX IF NOT EXISTS idx_generated_contract_status_client
    ON contracts.generated_contract (contract_status, client_id);

-- Index for full-text searching on notes (substring search support)
CREATE INDEX IF NOT EXISTS idx_generated_contract_notes_btree
    ON contracts.generated_contract USING BTREE (notes);

-- Composite index for template template_name searching
CREATE INDEX IF NOT EXISTS idx_contract_template_name_status
    ON contracts.generated_contract (contract_status)
    INCLUDE (template_id);

-- Index for searching field values with substring matching
-- Helps with labelValues filtering on contract_field_value
CREATE INDEX IF NOT EXISTS idx_contract_field_value_field_value_btree
    ON contracts.contract_field_value USING BTREE (field_value);

-- Composite index for field value filtering (contract + field value)
CREATE INDEX IF NOT EXISTS idx_contract_field_value_contract_field
    ON contracts.contract_field_value (generated_contract_id, template_field_id)
    INCLUDE (field_value);

-- Index to optimize date range queries
CREATE INDEX IF NOT EXISTS idx_generated_contract_created_date_range
    ON contracts.generated_contract (created_at DESC);

-- Composite index for common search patterns (status + created_at + client_id)
CREATE INDEX IF NOT EXISTS idx_generated_contract_search_composite
    ON contracts.generated_contract (contract_status, client_id, created_at);

